# Generated by Django 3.2.18 on 2023-04-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
